from . import pc_builder
from . import product_template
from . import product_product
from . import sale_order
from . import sale_order_line
from . import stock_picking
from . import stock_move
from . import stock_quant
from . import stock_inventory
from . import stock_warehouse
from . import stock_location
from . import res_partner